FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# myFirstAPI Documentation

This doc provide all the specs about myFirstAPI project

# Groups Questions

Test Groups hashtag

## Questions Collection [/questions/{question_id}]

Test description in the collection

### List All Questions [GET]

+ Parameters

    + question_id: '1' (optional, string)ior
        + Members
            + '1'
            + '2'
            
+ Request 1
    + Parameters
        + question_id: 1

+ Response 200 (text/html)

        <html>
            <head>Test my Api</head>
            <body>
                <h1>This is a Simple GET response</h1>
                <p>Hello World!</p>
            </body>
        </html>
        
+ Request 2
    + Parameters
        + question_id: 2

+ Response 201 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
        
### Delete [DELETE]

+ Response 204

+ Parameters
    + question_id: 3 (number,optional) - ID of a question
        + Default: 3